####import turtle 
####jayden = turtle.Turtle()
####jayden.penup() 
####jayden.backward(200)
####jayden.pendown()
####jayden.color("blue") 
####jayden.begin_fill()
####jayden.forward(50)
####jayden.left(120)
####jayden.forward(100)
####jayden.end_fill()
####jayden.color("yellow")
####jayden.begin_fill()
####jayden.left(120)
####jayden.forward(100)
####jayden.left(120)
####jayden.forward(50)
####jayden.end_fill()

##import turtle
##sanjay = turtle.Turtle()
##sanjay.color("blue")
##sanjay.begin_fill()
##sanjay.forward(100)
##sanjay.left(90)
##sanjay.forward(100)
##sanjay.end_fill()
##sanjay.begin_fill()
##sanjay.color("red")
##sanjay.left(90)
##sanjay.forward(100)
##sanjay.left(90)
##sanjay.forward(100)
##sanjay.end_fill()

##import turtle
##mike = turtle.Turtle()
##mike.color('black')
##mike.pencolor('blue')
##mike.fillcolor('cyan')
##mike.begin_fill()
##mike.forward(50)
##mike.right(90)
##mike.forward(50)
##mike.end_fill()
##mike.pencolor('pink')
##mike.fillcolor('red')
##mike.begin_fill()
##mike.forward(50)
##mike.right(90)
##mike.forward(50)
##mike.end_fill()
##mike.pencolor('dark blue')
##mike.fillcolor('light blue')
##mike.begin_fill()
##mike.forward(50)
##mike.right(90)
##mike.forward(50)
##mike.end_fill()
##mike.pencolor('yellow')
##mike.fillcolor('green')
##mike.begin_fill()
##mike.forward(50)
##mike.right(90)
##mike.forward(50)
##mike.end_fill()

##import turtle
##mike = turtle.Turtle()
##mike.fillcolor('green')
##mike.pensize(15)
##mike.pencolor('black')
##mike.begin_fill()
##mike.circle(50)
##mike.end_fill()
##mike.penup()
##mike.forward(222)
##mike.pendown()
##mike.fillcolor('blue')
##mike.pensize(20)
##mike.pencolor('pink')
##mike.begin_fill()
##mike.circle(50)
##mike.end_fill()

####import turtle
####mike = turtle.Turtle()
####mike.fillcolor('green')
####mike.pensize(15)
####mike.pencolor('black')
####mike.begin_fill()
####mike.circle(100,90)
####mike.end_fill()
####mike.fillcolor('blue')
####mike.pencolor('pink')
####mike.begin_fill()
####mike.circle(100,90)
####mike.end_fill()
####mike.fillcolor('dark blue')
####mike.pensize(15)
####mike.pencolor('light blue')
####mike.begin_fill()
####mike.circle(100,90)
####mike.end_fill()
####mike.fillcolor('brown')
####mike.pencolor('red')
####mike.begin_fill()
####mike.circle(100,90)
####mike.end_fill()
####mike.pencolor('black')

import turtle
mike = turtle.Turtle()
mike.fillcolor('pink')
mike.pencolor('blue')
mike.begin_fill()
mike.forward(200)
mike.right(90)
mike.forward(100)
mike.right(90)
mike.end_fill()
mike.fillcolor('yellow')
mike.pencolor('black')
mike.begin_fill()
mike.forward(200)
mike.right(90)
mike.forward(100)
mike.right(90)
mike.end_fill()
