##import turtle
##julia = turtle.Turtle()
##julia.fillcolor("pink") 
##julia.pencolor("black") 
##julia.begin_fill()
##julia.circle(100) 
##julia.end_fill()

import turtle
chris = turtle.Turtle()
chris.write("(0,0)")
chris.goto(-300,0)
chris.write("(-300,0)")
chris.goto(300,0)
chris.write("(300,0)")
chris.penup()
chris.goto(0,-300)
chris.pendown()
chris.write("(0,-300)")
chris.pendown()
chris.goto(0,300)
chris.write("(0,300)")

a = turtle.Turtle()
##b = turtle.Turtle()
##c = turtle.Turtle()
##d = turtle.Turtle()
##e = turtle.Turtle()
##f = turtle.Turtle()
##g = turtle.Turtle()
##h = turtle.Turtle()
##i = turtle.Turtle()
##j = turtle.Turtle()
a.shape('turtle')
##b.shape('turtle')
##c.shape('turtle')
##d.shape('turtle')
##e.shape('turtle')
##a.shape('turtle')
##b.shape('turtle')
##c.shape('turtle')
##d.shape('turtle')
##e.shape('turtle')
a.penup()
a.color('blue')
a.goto(250,-250)
a.stamp()
a.write('(250,-250)')
a.color('green')
a.goto(0,-100)
a.stamp()
a.write('(0,-100)')
a.color('orange')
a.goto(-200,-100)
a.stamp()
a.write('(-200,-100)')
a.color('purple')
a.goto(-200,100)
a.stamp()
a.write('(-200,100)')
a.color('red')
a.goto(200,200)
a.stamp()
a.write('(200,200)')
a.color('pink')
a.goto(-50,200)
a.stamp()
a.write('(-50,200)')
a.color('cyan')
a.goto(-200,-300)
a.stamp()
a.write('(-200,-300)')
a.color('magenta')
a.goto(100,0)
a.stamp()
a.write('(100,0)')
a.color('yellow')
a.goto(0,100)
a.stamp()
a.write('(0,100)')
a.color('brown')
a.goto(-300,300)
a.stamp()
a.write('(-300,300)')
a.color('cyan')
a.goto(200,200)
a.pendown()
a.forward(100)
a.right(90)
a.forward(100)
a.right(90)
a.forward(100)
a.right(90)
a.forward(100)
a.right(90)
a.penup()
a.goto(300,-300)
a.pendown()
a.forward(100)
a.left(120)
a.forward(100)
a.left(120)
a.forward(100)
a.left(120)
a.penup()
a.goto(0,300)
a.fillcolor('green')
a.pencolor('blue')
a.pendown()
a.begin_fill()
a.circle(100)
a.end_fill()
