##import turtle
##t = turtle.Turtle()
##t.pensize(4)
##t.color("yellow")
##t.pencolor("black")
##t.begin_fill() 
##t.circle(100)
##t.end_fill()
##t.color("black")
##t.penup()
##t.goto(-50,80)
##t.begin_fill()
##t.circle(20)
##t.end_fill()
##t.goto(50,80)
##t.begin_fill()
##t.circle(20)
##t.end_fill()
##t.goto(0,40)
##t.color("pink")
##t.begin_fill()
##t.circle(10)
##t.end_fill()
####import turtle
####tina = turtle.Turtle()
####tina.color("green")
####tina.fillcolor('brown')
####jamie = turtle.Turtle()
####jamie.color("blue")
####jamie.fillcolor('cyan')
####omar = turtle.Turtle()
####omar.color("red")
####omar.fillcolor('pink')
####tina.speed(1)
####jamie.speed(5)
####omar.speed(0)
####tina.forward(300) 
####jamie.forward(200) 
####omar.forward(100)
####tina.begin_fill()
####tina.left(120)
####tina.forward(100)
####tina.left(120)
####tina.forward(100)
####tina.left(120)
####tina.forward(100)
####tina.end_fill()
####jamie.begin_fill()
####jamie.backward(40)
####jamie.circle(50)
####jamie.forward(40)
####jamie.end_fill()
####omar.begin_fill()
####omar.left(90)
####omar.forward(100)
####omar.left(90)
####omar.forward(100)
####omar.left(90)
####omar.forward(100)
####omar.left(90)
####omar.forward(100)
####omar.end_fill()

import turtle
a = turtle.Turtle()
a.color('magenta')
b = turtle.Turtle()
b.color('cyan')
c = turtle.Turtle()
c.color('blue')
d = turtle.Turtle()
d.color('pink')
e = turtle.Turtle()
e.color('red')
f = turtle.Turtle()
f.color('brown')
a.shape('turtle')
b.shape('turtle')
c.shape('turtle')
d.shape('turtle')
e.shape('turtle')
f.shape('turtle')
a.penup()
b.penup()
c.penup()
d.penup()
e.penup()
f.penup()
a.forward(20)
b.forward(40)
c.forward(80)
d.forward(120)
e.forward(160)
f.forward(200)
