import turtle
mike = turtle.Turtle()
bob = turtle.Turtle()
mike.color('cyan')
mike.penup()
bob.penup()
bob.color('blue')
mike.goto(0,150)
bob.goto(0,-150)
mike.pendown()
mike.circle(100)
mike.penup()
bob.write('1 done,4 to go!')
mike.right(72)
mike.pendown()
mike.circle(100)
mike.penup()
bob.right(90)
bob.forward(10)
bob.write('2 done,3 to go!')
mike.right(72)
mike.pendown()
mike.circle(100)
mike.penup()
bob.forward(10)
bob.write('3 done,2 to go!')
mike.right(72)
mike.pendown()
mike.circle(100)
mike.penup()
bob.forward(10)
bob.write('4 done,1 to go!')
mike.right(72)
mike.pendown()
mike.circle(100)
mike.penup()
bob.forward(10)
bob.write('5 done,0 to go!')
bob.forward(20)
bob.pensize(10)
mike.color('red')
bob.color('orange')
bob.write('Great job, Mike!')
mike.right(72)
mike.penup()
mike.forward(150)
mike.write('Thanks, Bob!')
