##import turtle
##kayla = turtle.Turtle()
##obie = turtle.Turtle()
##john = turtle.Turtle()
##holly = turtle.Turtle() 
##kayla.color("red")
##obie.color("green")
##john.color("purple")
##holly.color("orange") 
##kayla.speed(1)
##obie.speed(0)
##john.speed(4) 
##kayla.goto(0,100) 
##obie.goto(100, 0) 
##john.goto(-100, 0)
##holly.goto(0, -100)
##kayla.hideturtle() 
####import turtle
####sasha = turtle.Turtle()
####screen = turtle.Screen()
####screen.bgcolor("yellow")
####sasha.forward(100) 
####sasha.right(120)
####sasha.forward(100)
####sasha.right(120)
####sasha.forward(100)
####screen.reset() 
####sasha.forward(100)
####screen.clear()
import turtle
mike = turtle.Turtle()
screen = turtle.Screen()
screen.bgcolor("light blue")
screen.setup(700,500)
mike.penup()
mike.color('red')
mike.speed(0)
mike.fillcolor('red')
mike.goto(0,-300)
mike.pendown()
mike.begin_fill()
mike.circle(175)
mike.end_fill()
mike.color('orange')
mike.fillcolor('orange')
mike.begin_fill()
mike.circle(150)
mike.end_fill()
mike.color('yellow')
mike.fillcolor('yellow')
mike.begin_fill()
mike.circle(125)
mike.end_fill()
mike.color('green')
mike.fillcolor('green')
mike.begin_fill()
mike.circle(100)
mike.end_fill()
mike.color('blue')
mike.fillcolor('blue')
mike.begin_fill()
mike.circle(75)
mike.end_fill()
mike.color('purple')
mike.fillcolor('purple')
mike.begin_fill()
mike.circle(50)
mike.end_fill()
mike.color('light blue')
mike.fillcolor('light blue')
mike.begin_fill()
mike.circle(35)
mike.end_fill()
mike.penup()
mike.color('white')
mike.fillcolor('white')
mike.speed(1)
mike.goto(0,150)
mike.begin_fill()
mike.pendown()
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.circle(100,50)
mike.right(40)
mike.end_fill()
