import turtle
mike = turtle.Turtle()
mike.penup()
mike.backward(300)
mike.pendown()
mike.left(90)
mike.forward(300)
mike.right(180)
mike.forward(600)
mike.left(90)
mike.forward(300)
mike.penup()
mike.forward(100)
mike.pendown()
mike.color('cyan')
mike.pensize('15')
mike.circle(150)

