import turtle
mike = turtle.Turtle()
mike.shape('circle')
mike.penup()
mike.backward(300)
mike.pendown()
mike.left(90)
mike.forward(150)
mike.right(180)
mike.forward(300)
mike.left(90)
mike.forward(150)
mike.penup()
mike.forward(100)
mike.pendown()
mike.color('cyan')
mike.pensize('15')
mike.shape('square')
mike.circle(75)
mike.penup()
mike.color('sky blue')
mike.shape('arrow')
mike.pensize('19')
mike.forward(100)
mike.pendown()
mike.left(90)
mike.forward(300)
mike.right(180)
mike.forward(300)
mike.left(90)
mike.forward(150)
